#Uncomment the line that has your car
#Only one car is supported right now, if you uncomment multiple cars then only
#The last car will be used

#Example:
car_type = 'Accord' #Honda - Accord

#car_type = 'CL' #Acura - CL
#car_type = 'EL' #Acura - EL
#car_type = 'Integra' #Acura - Integra
#car_type = 'Legend' #Acura - Legend
#car_type = 'MDX' #Acura - MDX
#car_type = 'RSX' #Acura - RSX
#car_type = 'TL' #Acura - TL
#car_type = 'Vigor' #Acura - Vigor
#car_type = '4000' #Audi - 4000
#car_type = '90' #Audi - 90
#car_type = '90 Quattro' #Audi - 90 Quattro
#car_type = 'A4' #Audi - A4
#car_type = 'A6' #Audi - A6
#car_type = '318 i' #BMW - 318 i
#car_type = '323 i' #BMW - 323 i
#car_type = '325 i' #BMW - 325 i
#car_type = '528 i' #BMW - 528 i
#car_type = '530 i' #BMW - 530 i
#car_type = '740 i' #BMW - 740 i
#car_type = 'Allure' #Buick - Allure
#car_type = 'Century' #Buick - Century
#car_type = 'Lacrosse' #Buick - Lacrosse
#car_type = 'Lesabre' #Buick - Lesabre
#car_type = 'Park Ave' #Buick - Park Ave
#car_type = 'Rainier' #Buick - Rainier
#car_type = 'Regal' #Buick - Regal
#car_type = 'Rendezvous' #Buick - Rendezvous
#car_type = 'Skylark' #Buick - Skylark
#car_type = 'Terraza' #Buick - Terraza
#car_type = 'Catera' #Cadillac - Catera
#car_type = 'CTS' #Cadillac - CTS
#car_type = 'Seville' #Cadillac - Seville
#car_type = '1500' #Chev - 1500
#car_type = '2500' #Chev - 2500
#car_type = 'Astro' #Chev - Astro
#car_type = 'Aveo' #Chev - Aveo
#car_type = 'Camaro' #Chev - Camaro
#car_type = 'Cavalier' #Chev - Cavalier
#car_type = 'Celebrity' #Chev - Celebrity
#car_type = 'Cobalt' #Chev - Cobalt
#car_type = 'Epica' #Chev - Epica
#car_type = 'Express 2500' #Chev - Express 2500
#car_type = 'Express 3500' #Chev - Express 3500
#car_type = 'HHR' #Chev - HHR
#car_type = 'Impala' #Chev - Impala
#car_type = 'Lumina' #Chev - Lumina
#car_type = 'Malibu' #Chev - Malibu
#car_type = 'Monte Carlo' #Chev - Monte Carlo
#car_type = 'Monza' #Chev - Monza
#car_type = 'Nova' #Chev - Nova
#car_type = 'Optra' #Chev - Optra
#car_type = 'S10' #Chev - S10
#car_type = 'S10 Blazer' #Chev - S10 Blazer
#car_type = 'Sprint' #Chev - Sprint
#car_type = 'Suburban' #Chev - Suburban
#car_type = 'Tahoe' #Chev - Tahoe
#car_type = 'Tracker' #Chev - Tracker
#car_type = 'Trail Blazer' #Chev - Trail Blazer
#car_type = 'Uplander' #Chev - Uplander
#car_type = 'Venture' #Chev - Venture
#car_type = '300 M' #Chrysler - 300 M
#car_type = 'Cirrus' #Chrysler - Cirrus
#car_type = 'Concorde' #Chrysler - Concorde
#car_type = 'Dynasty' #Chrysler - Dynasty
#car_type = 'Intrepid' #Chrysler - Intrepid
#car_type = 'Le Baron' #Chrysler - Le Baron
#car_type = 'New Yorker' #Chrysler - New Yorker
#car_type = 'Pacifica' #Chrysler - Pacifica
#car_type = 'Pt Cruiser' #Chrysler - Pt Cruiser
#car_type = 'Sebring' #Chrysler - Sebring
#car_type = 'Avenger' #Dodge - Avenger
#car_type = 'B150' #Dodge - B150
#car_type = 'B250' #Dodge - B250
#car_type = 'Caliber' #Dodge - Caliber
#car_type = 'Caravan' #Dodge - Caravan
#car_type = 'Charger' #Dodge - Charger
#car_type = 'Colt' #Dodge - Colt
#car_type = 'D50' #Dodge - D50
#car_type = 'Dakota' #Dodge - Dakota
#car_type = 'Durango' #Dodge - Durango
#car_type = 'Neon' #Dodge - Neon
#car_type = 'Omni' #Dodge - Omni
#car_type = 'Ram 150' #Dodge - Ram 150
#car_type = 'Ram 1500' #Dodge - Ram 1500
#car_type = 'Ram 250' #Dodge - Ram 250
#car_type = 'Ram 2500' #Dodge - Ram 2500
#car_type = 'Shadow' #Dodge - Shadow
#car_type = 'Spirit' #Dodge - Spirit
#car_type = 'Stratus' #Dodge - Stratus
#car_type = 'Talon' #Eagle - Talon
#car_type = 'Aerostar' #Ford - Aerostar
#car_type = 'Aspire' #Ford - Aspire
#car_type = 'Bronco' #Ford - Bronco
#car_type = 'Bronco II' #Ford - Bronco II
#car_type = 'Contour' #Ford - Contour
#car_type = 'E150' #Ford - E150
#car_type = 'E250' #Ford - E250
#car_type = 'E350' #Ford - E350
#car_type = 'Escape' #Ford - Escape
#car_type = 'Escort' #Ford - Escort
#car_type = 'Expedition' #Ford - Expedition
#car_type = 'Explorer' #Ford - Explorer
#car_type = 'F150' #Ford - F150
#car_type = 'F250' #Ford - F250
#car_type = 'F350' #Ford - F350
#car_type = 'Festiva' #Ford - Festiva
#car_type = 'Focus' #Ford - Focus
#car_type = 'Freestar' #Ford - Freestar
#car_type = 'Freestyle' #Ford - Freestyle
#car_type = 'Fusion' #Ford - Fusion
#car_type = 'LTD' #Ford - LTD
#car_type = 'Mustang' #Ford - Mustang
#car_type = 'Probe' #Ford - Probe
#car_type = 'Ranger' #Ford - Ranger
#car_type = 'Taurus' #Ford - Taurus
#car_type = 'Tempo' #Ford - Tempo
#car_type = 'Thunderbird' #Ford - Thunderbird
#car_type = 'Windstar' #Ford - Windstar
#car_type = 'Metro' #Geo - Metro
#car_type = '1500' #GMC - 1500
#car_type = '2500' #GMC - 2500
#car_type = 'Canyon' #GMC - Canyon
#car_type = 'Envoy' #GMC - Envoy
#car_type = 'G20' #GMC - G20
#car_type = 'S10' #GMC - S10
#car_type = 'S10 Jimmy' #GMC - S10 Jimmy
#car_type = 'Safari' #GMC - Safari
#car_type = 'Savana' #GMC - Savana
#car_type = 'Suburban' #GMC - Suburban
#car_type = 'Yukon' #GMC - Yukon
#car_type = 'Accord' #Honda - Accord
#car_type = 'Civic' #Honda - Civic
#car_type = 'CR-V' #Honda - CR-V
#car_type = 'Odyssey' #Honda - Odyssey
#car_type = 'Pilot' #Honda - Pilot
#car_type = 'Prelude' #Honda - Prelude
#car_type = 'Accent' #Hyundai - Accent
#car_type = 'Elantra' #Hyundai - Elantra
#car_type = 'Santa Fe' #Hyundai - Santa Fe
#car_type = 'Scoupe' #Hyundai - Scoupe
#car_type = 'Sonata' #Hyundai - Sonata
#car_type = 'Tiburon' #Hyundai - Tiburon
#car_type = 'Tucson' #Hyundai - Tucson
#car_type = 'XG350' #Hyundai - XG350
#car_type = 'J30' #Infiniti - J30
#car_type = 'Qx4' #Infiniti - Qx4
#car_type = 'Pup' #Isuzu - Pup
#car_type = 'Rodeo' #Isuzu - Rodeo
#car_type = 'Trooper' #Isuzu - Trooper
#car_type = 'S-Type' #Jaguar - S-Type
#car_type = 'Cherokee' #Jeep - Cherokee
#car_type = 'Liberty' #Jeep - Liberty
#car_type = 'YJ' #Jeep - YJ
#car_type = 'Magentis' #Kia - Magentis
#car_type = 'Rio' #Kia - Rio
#car_type = 'Rio 5' #Kia - Rio 5
#car_type = 'Rondo' #Kia - Rondo
#car_type = 'Sedona' #Kia - Sedona
#car_type = 'Sephia' #Kia - Sephia
#car_type = 'Sorento' #Kia - Sorento
#car_type = 'Spectra' #Kia - Spectra
#car_type = 'Spectra 5' #Kia - Spectra 5
#car_type = 'Sportage' #Kia - Sportage
#car_type = 'Discovery' #Land Rover - Discovery
#car_type = 'Freelander' #Land Rover - Freelander
#car_type = 'Range Rover' #Land Rover - Range Rover
#car_type = 'ES300' #Lexus - ES300
#car_type = 'Continental' #Lincoln - Continental
#car_type = 'LS' #Lincoln - LS
#car_type = 'Mark 5' #Lincoln - Mark 5
#car_type = 'Navigator' #Lincoln - Navigator
#car_type = 'Town Car' #Lincoln - Town Car
#car_type = '323' #Mazda - 323
#car_type = '626' #Mazda - 626
#car_type = 'B2200' #Mazda - B2200
#car_type = 'B2600' #Mazda - B2600
#car_type = 'Mazda 3' #Mazda - Mazda 3
#car_type = 'Mazda 5' #Mazda - Mazda 5
#car_type = 'Mazda 6' #Mazda - Mazda 6
#car_type = 'Miata' #Mazda - Miata
#car_type = 'Millenia' #Mazda - Millenia
#car_type = 'Mpv' #Mazda - Mpv
#car_type = 'Mx3' #Mazda - Mx3
#car_type = 'Protege' #Mazda - Protege
#car_type = 'Protege 5' #Mazda - Protege 5
#car_type = 'Tribute' #Mazda - Tribute
#car_type = '240 D' #Mercedes - 240 D
#car_type = '420 SEL' #Mercedes - 420 SEL
#car_type = '450 SLC' #Mercedes - 450 SLC
#car_type = 'C220' #Mercedes - C220
#car_type = 'C230' #Mercedes - C230
#car_type = 'C240' #Mercedes - C240
#car_type = 'C280' #Mercedes - C280
#car_type = 'E320' #Mercedes - E320
#car_type = 'ML 430' #Mercedes - ML 430
#car_type = 'S420' #Mercedes - S420
#car_type = 'Capri' #Mercury - Capri
#car_type = 'Cougar' #Mercury - Cougar
#car_type = 'Marquis' #Mercury - Marquis
#car_type = 'Mystique' #Mercury - Mystique
#car_type = 'Sable' #Mercury - Sable
#car_type = 'Topaz' #Mercury - Topaz
#car_type = 'Eclipse' #Mitsubishi - Eclipse
#car_type = 'Galant' #Mitsubishi - Galant
#car_type = 'Lancer' #Mitsubishi - Lancer
#car_type = 'Outlander' #Mitsubishi - Outlander
#car_type = '200SX' #Nissan - 200SX
#car_type = 'Altima' #Nissan - Altima
#car_type = 'Maxima' #Nissan - Maxima
#car_type = 'Micra' #Nissan - Micra
#car_type = 'Murano' #Nissan - Murano
#car_type = 'Pathfinder' #Nissan - Pathfinder
#car_type = 'Quest' #Nissan - Quest
#car_type = 'Sentra' #Nissan - Sentra
#car_type = 'Stanza' #Nissan - Stanza
#car_type = 'Truck' #Nissan - Truck
#car_type = 'Versa' #Nissan - Versa
#car_type = 'Xterra' #Nissan - Xterra
#car_type = 'Achieva' #Oldsmobile - Achieva
#car_type = 'Alero' #Oldsmobile - Alero
#car_type = 'Aurora' #Oldsmobile - Aurora
#car_type = 'Calais' #Oldsmobile - Calais
#car_type = 'Ciera' #Oldsmobile - Ciera
#car_type = 'Cutlass' #Oldsmobile - Cutlass
#car_type = 'Eighty Eight' #Oldsmobile - Eighty Eight
#car_type = 'Intrigue' #Oldsmobile - Intrigue
#car_type = 'Ninety Eight' #Oldsmobile - Ninety Eight
#car_type = 'Silhouette' #Oldsmobile - Silhouette
#car_type = 'Toronado' #Oldsmobile - Toronado
#car_type = 'Breeze' #Plymouth - Breeze
#car_type = 'Duster' #Plymouth - Duster
#car_type = 'Reliant' #Plymouth - Reliant
#car_type = 'Sundance' #Plymouth - Sundance
#car_type = 'Vista' #Plymouth - Vista
#car_type = 'Volare' #Plymouth - Volare
#car_type = 'Voyager' #Plymouth - Voyager
#car_type = 'Bonneville' #Pontiac - Bonneville
#car_type = 'Firefly' #Pontiac - Firefly
#car_type = 'G3' #Pontiac - G3
#car_type = 'G5' #Pontiac - G5
#car_type = 'G6' #Pontiac - G6
#car_type = 'Grand Am' #Pontiac - Grand Am
#car_type = 'Grand Prix' #Pontiac - Grand Prix
#car_type = 'Montana' #Pontiac - Montana
#car_type = 'Pursuit' #Pontiac - Pursuit
#car_type = 'Sunbird' #Pontiac - Sunbird
#car_type = 'Sunfire' #Pontiac - Sunfire
#car_type = 'Torrent' #Pontiac - Torrent
#car_type = 'Trans Sport' #Pontiac - Trans Sport
#car_type = 'Vibe' #Pontiac - Vibe
#car_type = 'Wave' #Pontiac - Wave
#car_type = '924' #Porsche - 924
#car_type = '9-2 X' #Saab - 9-2 X
#car_type = '9-5' #Saab - 9-5
#car_type = 'Astra' #Saturn - Astra
#car_type = 'Ion' #Saturn - Ion
#car_type = 'L300' #Saturn - L300
#car_type = 'LS1' #Saturn - LS1
#car_type = 'LS2' #Saturn - LS2
#car_type = 'LW2' #Saturn - LW2
#car_type = 'SC1' #Saturn - SC1
#car_type = 'SL1' #Saturn - SL1
#car_type = 'Vue' #Saturn - Vue
#car_type = 'Domingo' #Subaru - Domingo
#car_type = 'Forester' #Subaru - Forester
#car_type = 'GL' #Subaru - GL
#car_type = 'Impreza' #Subaru - Impreza
#car_type = 'Justy' #Subaru - Justy
#car_type = 'Legacy' #Subaru - Legacy
#car_type = 'Loyale' #Subaru - Loyale
#car_type = 'Aerio' #Suzuki - Aerio
#car_type = 'Esteem' #Suzuki - Esteem
#car_type = 'Sidekick' #Suzuki - Sidekick
#car_type = 'Swift' #Suzuki - Swift
#car_type = 'SX4' #Suzuki - SX4
#car_type = 'Vitara' #Suzuki - Vitara
#car_type = '4 Runner' #Toyota - 4 Runner
#car_type = 'Avalon' #Toyota - Avalon
#car_type = 'Camry' #Toyota - Camry
#car_type = 'Celica' #Toyota - Celica
#car_type = 'Corolla' #Toyota - Corolla
#car_type = 'Echo' #Toyota - Echo
#car_type = 'Paseo' #Toyota - Paseo
#car_type = 'Previa' #Toyota - Previa
#car_type = 'Prius' #Toyota - Prius
#car_type = 'Rav 4' #Toyota - Rav 4
#car_type = 'Sienna' #Toyota - Sienna
#car_type = 'Supra' #Toyota - Supra
#car_type = 'T100' #Toyota - T100
#car_type = 'Tacoma' #Toyota - Tacoma
#car_type = 'Tercel' #Toyota - Tercel
#car_type = 'Van Wagon' #Toyota - Van Wagon
#car_type = 'Yaris' #Toyota - Yaris
#car_type = 'Golf' #Volkswagen - Golf
#car_type = 'Jetta' #Volkswagen - Jetta
#car_type = 'Passat' #Volkswagen - Passat
#car_type = 'Scirocco' #Volkswagen - Scirocco
#car_type = '740' #Volvo - 740
#car_type = '850' #Volvo - 850
#car_type = '940' #Volvo - 940
#car_type = 'S40' #Volvo - S40
#car_type = 'S60' #Volvo - S60
#car_type = 'S70' #Volvo - S70
#car_type = 'S80' #Volvo - S80
#car_type = 'V40' #Volvo - V40
#car_type = 'V70' #Volvo - V70

#Can't look for a car you didn't define!
try:
    car_type
except Exception as e:
    print("ERROR: Make sure to select a car in carList.py by uncommenting the line for your car.")
    quit()
